#!/bin/bash

set -e
echo $LPASS_USERNAME
if [[ $(lpass status) = 'Not logged in.' ]]; then
  if [ -n $LPASS_USERNAME ]; then
    lpass login $LPASS_USERNAME
  else
    echo 'Please login first.'
    exit 0
  fi
fi

set +e

passinfo=$(lpass ls --format '%an - %au - %ai' | fzf)
passid=$(echo "$passinfo" | awk -F' - ' '{ print $3 }')
echo -n $(lpass show -p $passid) | pbcopy
